services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package

cache:
  paths:
    - node_modules/
    - dist/

deploy_stage:
  stage: build
  image: trion/ng-cli-karma
  artifacts:
    paths:
      - dist/
  script:
    - rm ./package-lock.json
    - yarn
    - yarn build --progress false --prod
  only:
    - tags

    
docker-build:
  stage: package
  image: docker:latest
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PSW registry.gitlab.com
    - docker build -t registry.gitlab.com/highimpact/mtsuite/mtsuites-frontend .
    - docker push registry.gitlab.com/highimpact/mtsuite/mtsuites-frontend:latest
  only:
    - tags
